# Generated by Django 4.1.7 on 2023-02-18 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='bookproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.product'),
        ),
    ]
